import AVFoundation
import Foundation

/// The app's three UI sound cues, and the policy that decides whether one actually plays.
///
/// The Notch is an ambient app: it lives in hardware trim the user is not looking at, so audio
/// is the only channel that reaches them while they are working somewhere else. That makes it
/// valuable and makes it dangerous — a cue that fires too often is worse than no cue at all,
/// because the user turns the feature off and then misses the one event that mattered.
///
/// So the rules here are deliberately strict:
///
/// - **Three cues, not five.** Panel expand/collapse deliberately has none. It fires on hover,
///   on every scrub of the pointer past the notch, and again whenever an approval takes the
///   panel over — which would double up with ``Cue/approvalRequested`` on the one event that
///   most needs to be heard clearly. It is also pure chrome: the user just caused it and is
///   already looking at it, so a sound carries no information.
/// - **Rate-limited at the leading edge.** The first cue in a burst plays immediately; the rest
///   are dropped, not queued. Three agents finishing at once is one event to a human.
/// - **Silent by construction in headless mode.** See ``isHeadless``.
/// - **Failure is always silence.** A missing or corrupt file logs once and is never retried.
///
/// The cue files themselves are generated by `tools/generate-sounds.py` and are original
/// synthesised tones — see that script for the waveform and envelope of each.
@MainActor
final class SoundEffects {
    static let shared = SoundEffects()

    // MARK: - Cues

    enum Cue: CaseIterable {
        /// An agent is blocked on a permission request. The user is the only thing standing
        /// between the agent and progress, so this is the one cue that earns interruption.
        case approvalRequested
        /// An agent is waiting on an answer that is not a permission decision.
        case questionAsked
        /// An agent finished or went idle. Informational.
        case sessionFinished

        fileprivate var resourceName: String {
            switch self {
            case .approvalRequested: "sfx-approval"
            case .questionAsked: "sfx-question"
            case .sessionFinished: "sfx-done"
            }
        }

        /// Whether the cue survives the user asking the system for less sensory feedback.
        ///
        /// Only the blocking cue is essential. This decides who wins a collision — it is
        /// deliberately *not* wired to any accessibility preference; see ``play(_:now:)``.
        fileprivate var isEssential: Bool {
            self == .approvalRequested
        }

        /// Minimum gap between two firings of *this* cue. Generous on the informational cues
        /// because their underlying events arrive in bursts (a fan-out of subagents all
        /// stopping, an agent emitting several notifications while it settles).
        fileprivate var cooldown: TimeInterval {
            switch self {
            case .approvalRequested: 0.75
            case .questionAsked, .sessionFinished: 2.5
            }
        }

        /// Higher wins when two cues collide inside ``minimumSpacing``.
        fileprivate var priority: Int {
            isEssential ? 1 : 0
        }
    }

    // MARK: - Preference

    /// User-facing mute switch. There is no settings UI yet, so this is the whole surface:
    /// on by default, and flippable from a debugger or with
    /// `defaults write com.thenotch.TheNotch NotchSoundEffectsEnabled -bool false`.
    ///
    /// Defaulting to on is the right call for a cue set this quiet and this rare — the cues
    /// only fire on agent events the user explicitly wired hooks up for.
    var isEnabled: Bool {
        get { defaults.bool(forKey: Self.enabledDefaultsKey) }
        set { defaults.set(newValue, forKey: Self.enabledDefaultsKey) }
    }

    static let enabledDefaultsKey = "NotchSoundEffectsEnabled"

    // MARK: - Internals

    /// Longer than the longest cue file (250 ms), so two cues can never overlap. A collision
    /// inside this window is resolved by priority rather than by mixing.
    private static let minimumSpacing: TimeInterval = 0.30

    private let defaults: UserDefaults
    private let bundle: Bundle

    private var players: [Cue: AVAudioPlayer] = [:]
    /// Cues whose file could not be loaded. Recorded so a missing resource costs one failed
    /// load and one log line for the life of the process, not one per event.
    private var unavailable: Set<Cue> = []

    private var lastPlayed: [Cue: Date] = [:]
    private var lastPlayedAny: (cue: Cue, at: Date)?

    init(defaults: UserDefaults = .standard, bundle: Bundle = .main) {
        self.defaults = defaults
        self.bundle = bundle
        defaults.register(defaults: [Self.enabledDefaultsKey: true])
    }

    /// Loads and prepares every cue so the first real event is not delayed by disk I/O and
    /// audio-unit setup. Safe to call more than once; a no-op when headless or muted.
    func preload() {
        guard !Self.isHeadless, isEnabled else { return }
        for cue in Cue.allCases {
            _ = player(for: cue)
        }
    }

    /// Plays `cue` if every gate allows it. Never throws, never blocks, and does nothing at all
    /// when the answer is no — callers are expected to fire and forget.
    /// Deliberately not gated on Reduce Motion. That preference is a vestibular accommodation
    /// and says nothing about audio; macOS keeps motion and sound separate precisely because
    /// they are separate needs. Gating on it would mean a user who enables Reduce Motion
    /// silently loses two of the three cues, with no discoverable cause and no way to get them
    /// back short of turning off an unrelated accessibility setting. ``isEnabled`` is the
    /// control for "I do not want sounds".
    func play(_ cue: Cue, now: Date = Date()) {
        guard !Self.isHeadless else { return }
        guard isEnabled else { return }

        if let previous = lastPlayed[cue], now.timeIntervalSince(previous) < cue.cooldown {
            return
        }

        if let last = lastPlayedAny, now.timeIntervalSince(last.at) < Self.minimumSpacing {
            // Something is already sounding. Only a higher-priority cue may cut in, and when
            // it does it stops the incumbent rather than layering on top of it.
            guard cue.priority > last.cue.priority else { return }
            stopAll()
        }

        guard let player = player(for: cue) else { return }
        player.currentTime = 0
        guard player.play() else { return }

        lastPlayed[cue] = now
        lastPlayedAny = (cue, now)
    }

    /// Halts anything currently sounding. Used when a higher-priority cue preempts, and
    /// available for teardown.
    func stopAll() {
        for player in players.values where player.isPlaying {
            player.stop()
        }
    }

    // MARK: - Gates

    /// True when the process is rendering rather than running.
    ///
    /// `FrameDump` builds real `NotchRootView`s offscreen and exits; it must stay silent and
    /// headless so it can run on a build agent. This reads the same environment variable
    /// `FrameDump` does instead of calling into it, so the guard holds even for code paths
    /// that run before — or without — the dump itself. Tests are covered for the same reason:
    /// a unit-test run should not make noise.
    private static var isHeadless: Bool {
        if ProcessInfo.processInfo.environment["NOTCH_FRAMES"] != nil { return true }
        if NSClassFromString("XCTestCase") != nil { return true }
        return false
    }

    // MARK: - Loading

    private func player(for cue: Cue) -> AVAudioPlayer? {
        if let cached = players[cue] { return cached }
        guard !unavailable.contains(cue) else { return nil }

        guard let url = bundle.url(forResource: cue.resourceName, withExtension: "wav") else {
            markUnavailable(cue, reason: "not found in bundle")
            return nil
        }

        do {
            let player = try AVAudioPlayer(contentsOf: url)
            player.volume = 1.0
            player.prepareToPlay()
            players[cue] = player
            return player
        } catch {
            markUnavailable(cue, reason: error.localizedDescription)
            return nil
        }
    }

    /// Degrades to silence. Never asserts: a broken sound file is a cosmetic problem, and
    /// crashing a debug build over one would be a far worse bug than the missing cue.
    private func markUnavailable(_ cue: Cue, reason: String) {
        unavailable.insert(cue)
        FileHandle.standardError.write(
            Data("SoundEffects: \(cue.resourceName).wav unavailable (\(reason)); staying silent\n".utf8)
        )
    }
}
